version: "3.3"
services:
  app-frame:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app-frame/dist/:/var/www/localhost/public/
    ports:
      - "8080:80"
  inspire:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./inspire/dist/:/var/www/localhost/public/
    ports:
      - "8081:80"
  checkout:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./checkout/dist/:/var/www/localhost/public/
    ports:
      - "8082:80"
  product:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./product/dist/:/var/www/localhost/public/
    ports:
      - "8083:80"
  app-registry:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app-registry.json:/var/www/localhost/public/app-registry.json
    ports:
      - "8084:80"
